### ISSUE TITLE
plagiarised code!

### ISSUE THREAD

**Issue by raghukul01** [ayush268/cpdb-backend-gtk3#1]
Following book contains exact same code snippet (as in gtk-print.c), atleast cite that.
link: [https://goo.gl/Qyt1Do]

**Comment by ayush268** [comment]
That code is for learning and testing gtk3 as is the motive of the book that you have shared the link to, it is picked up from various sources and as you can see the repository is not complete, it has just 2 commits.
Please don't accuse people without knowing the reason!

**Comment by raghukul01** [comment]
![a8383556-1a83-481f-aec8-54574e704856](https://user-images.githubusercontent.com/24277086/42871188-550538e8-8a97-11e8-8e6a-da85b8954b7c.jpeg)

Please don't close the issue before addressing it!

"That code is for learning and testing gtk3 as is the motive of the book that you have shared the link to"
I agree, but that doesn't give anyone the right to copy it and call it as their own.
Book has a copyright which one can find at the start of the book (see attached image).

**Comment by parvmor** [comment]
First of all no one is accusing you of anything. He was merely trying to help. If help of fellow contributors is not appreciated then you might consider leaving open source development (make the repo private or something). Secondly, the code is not picked from various sources, rather has been copied line to line (even comments) from the book. You are violating the copyright license of this book by sharing this snippet. Please address the issue properly before abruptly closing it.
